version: "3.8"

services:
  deno-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: deno-backend
    command: deno run --allow-net --allow-env --allow-sys --watch src/main.ts
    working_dir: /usr/src/app
    volumes:
      - ./deno-backend:/usr/src/app:delegated # Sync local files with the container
      - deno-cache:/deno-dir
    ports:
      - "5000:5000"
    environment:
      - DENO_ENV=development

volumes:
  deno-cache:
